---
- hosts: local
  become: yes

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Build Docker image
      shell: docker build -t my-python-app . -f Dockerfile
      args:
        chdir: "{{ lookup('env', 'GITHUB_WORKSPACE') }}/app"

    - name: Run Docker container
      shell: docker run --rm my-python-app

